*TO DO*
- one hot na Y, four g, wifi, blue
- skalowanie?
- model

In [2]:
import pandas as pd
import keras
import sklearn as sk
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

c:\Users\Miszmosz\Desktop\PWR-studia\sem_3\ML_kurs\projekt\MobileTech\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

## Wczytanie danych

In [3]:
phone_data = pd.read_csv("dataset.csv")

In [4]:
phone_data.head()

,Unnamed: 0,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,0,842,no,2.2,0,1,no,7,0.6,188,...,20,756,2549.0,9,7,19.0,0,0,wifi,medium cost
1,1,1021,yes,0.5,1,0,yes,53,0.7,136,...,905,1988,2631.0,17,3,7.0,1,1,no_wifi,high cost
2,2,563,yes,0.5,1,2,yes,41,0.9,145,...,1263,1716,2603.0,11,2,9.0,1,1,no_wifi,high cost
3,3,615,yes,2.5,0,0,no,10,0.8,131,...,1216,1786,2769.0,16,8,11.0,1,0,no_wifi,high cost
4,4,1821,yes,1.2,0,13,yes,44,0.6,141,...,1208,1212,1411.0,8,2,15.0,1,1,no_wifi,medium cost

In [5]:
phone_data['price_range'].value_counts()

price_range
low cost          485
high cost         484
medium cost       483
very high cost    483
Name: count, dtype: int64

In [6]:
phone_data.describe()

,Unnamed: 0,battery_power,clock_speed,dual_sim,fc,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen
count,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1913.000000,1935.000000,1935.000000,1873.000000,1935.000000,1935.000000
mean,997.788114,1240.282687,1.528889,0.509044,4.298708,32.115245,0.504703,140.209819,4.529716,9.932817,646.829457,1255.708527,2120.500784,12.322997,5.757623,10.998398,0.762274,0.501809
std,577.034770,438.590972,0.820332,0.500047,4.345792,18.161480,0.292660,35.480487,2.285474,6.057774,445.042126,434.465962,1083.400626,4.209676,4.333399,5.457734,0.425801,0.500126
min,0.000000,501.000000,0.500000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,0.000000,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000
25%,499.500000,853.500000,0.700000,0.000000,1.000000,16.000000,0.200000,109.000000,3.000000,5.000000,284.500000,880.000000,1205.000000,9.000000,2.000000,6.000000,1.000000,0.000000
50%,999.000000,1231.000000,1.500000,1.000000,3.000000,32.000000,0.500000,141.000000,4.000000,10.000000,567.000000,1251.000000,2131.000000,12.000000,5.000000,11.000000,1.000000,1.000000
75%,1493.500000,1617.000000,2.250000,1.000000,7.000000,48.000000,0.800000,170.000000,7.000000,15.000000,948.000000,1638.500000,3056.000000,16.000000,9.000000,16.000000,1.000000,1.000000
max,1999.000000,1998.000000,4.000000,1.000000,19.000000,64.000000,2.000000,200.000000,8.000000,20.000000,1960.000000,2298.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000

## Podział na cechy i etykiety

In [7]:
X = phone_data.drop(["price_range", "Unnamed: 0"], axis=1)
Y = phone_data["price_range"]

In [8]:
# from sklearn.model_selection import train_test_split

In [9]:
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

## Preprocessing

Usuwanie wierszy z nadmierną ilością nanów

In [10]:
phone_data = phone_data.drop(["Unnamed: 0"], axis=1)

In [11]:
phone_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1935 entries, 0 to 1934
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  1935 non-null   int64
 1   blue           1915 non-null   object
 2   clock_speed    1935 non-null   float64
 3   dual_sim       1935 non-null   int64
 4   fc             1935 non-null   int64
 5   four_g         1935 non-null   object
 6   int_memory     1935 non-null   int64
 7   m_dep          1935 non-null   float64
 8   mobile_wt      1935 non-null   int64
 9   n_cores        1935 non-null   int64
 10  pc             1935 non-null   int64
 11  px_height      1935 non-null   int64
 12  px_width       1935 non-null   int64
 13  ram            1913 non-null   float64
 14  sc_h           1935 non-null   int64
 15  sc_w           1935 non-null   int64
 16  talk_time      1873 non-null   float64
 17  three_g        1935 non-null   int64
 18  touch_screen   1935 non-null   int64
 19  wifi           1935 non-null   object
 20  price_range    1935 non-null   object
dtypes: float64(4), int64(13), object(4)
memory usage: 317.6+ KB

In [12]:
display(phone_data)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,no,2.2,0,1,no,7,0.6,188,2,...,20,756,2549.0,9,7,19.0,0,0,wifi,medium cost
1,1021,yes,0.5,1,0,yes,53,0.7,136,3,...,905,1988,2631.0,17,3,7.0,1,1,no_wifi,high cost
2,563,yes,0.5,1,2,yes,41,0.9,145,5,...,1263,1716,2603.0,11,2,9.0,1,1,no_wifi,high cost
3,615,yes,2.5,0,0,no,10,0.8,131,6,...,1216,1786,2769.0,16,8,11.0,1,0,no_wifi,high cost
4,1821,yes,1.2,0,13,yes,44,0.6,141,2,...,1208,1212,1411.0,8,2,15.0,1,1,no_wifi,medium cost
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,794,yes,0.5,1,0,yes,2,0.8,106,6,...,1222,1890,668.0,13,4,19.0,1,1,no_wifi,low cost
1931,1965,yes,2.6,1,0,no,39,0.2,187,4,...,915,1965,2032.0,11,10,16.0,1,1,wifi,high cost
1932,1911,no,0.9,1,1,yes,36,0.7,108,8,...,868,1632,3057.0,9,1,5.0,1,1,no_wifi,very high cost
1933,1512,no,0.9,0,4,yes,46,0.1,145,5,...,336,670,869.0,18,10,19.0,1,1,wifi,low cost
1934,510,yes,2.0,1,5,yes,45,0.9,168,6,...,483,754,3919.0,19,4,2.0,1,1,wifi,very high cost

In [13]:
def remove_nan(data, threshold=0.5):
    nan_df = data.isna()
    missing_val_row_percent = nan_df.mean(axis=1)
    return data[missing_val_row_percent <= threshold]

In [14]:
phone_data = remove_nan(phone_data)

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [16]:
text_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('one_hot', OneHotEncoder(sparse_output=False))
])

In [17]:
number_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="mean")),
    ('scaler', StandardScaler())
])

In [18]:
numeric_columns = phone_data.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [19]:
print(numeric_columns)

['battery_power', 'clock_speed', 'dual_sim', 'fc', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen']

In [20]:
ct = ColumnTransformer([
    ("text_pipe", text_pipeline, ["blue", "four_g", "wifi", "price_range"]),
    ("number_pipe", number_pipeline, numeric_columns)
])

ct.fit_transform(phone_data)

array([[ 1.        ,  0.        ,  1.        , ...,  1.49056925,
        -1.79067634, -1.00362414],
       [ 0.        ,  1.        ,  0.        , ..., -0.74483706,
         0.55844821,  0.99638895],
       [ 0.        ,  1.        ,  0.        , ..., -0.37226935,
         0.55844821,  0.99638895],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -1.11740478,
         0.55844821,  0.99638895],
       [ 1.        ,  0.        ,  0.        , ...,  1.49056925,
         0.55844821,  0.99638895],
       [ 0.        ,  1.        ,  0.        , ..., -1.67625636,
         0.55844821,  0.99638895]], shape=(1935, 27))

In [24]:
df_analyzed = pd.DataFrame(ct.fit_transform(phone_data), columns=ct.get_feature_names_out())

In [26]:
df_analyzed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1935 entries, 0 to 1934
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   text_pipe__blue_no                     1935 non-null   float64
 1   text_pipe__blue_yes                    1935 non-null   float64
 2   text_pipe__four_g_no                   1935 non-null   float64
 3   text_pipe__four_g_yes                  1935 non-null   float64
 4   text_pipe__wifi_no_wifi                1935 non-null   float64
 5   text_pipe__wifi_wifi                   1935 non-null   float64
 6   text_pipe__price_range_high cost       1935 non-null   float64
 7   text_pipe__price_range_low cost        1935 non-null   float64
 8   text_pipe__price_range_medium cost     1935 non-null   float64
 9   text_pipe__price_range_very high cost  1935 non-null   float64
 10  number_pipe__battery_power             1935 non-null   float64
 11  number_pipe__clock_speed               1935 non-null   float64
 12  number_pipe__dual_sim                  1935 non-null   float64
 13  number_pipe__fc                        1935 non-null   float64
 14  number_pipe__int_memory                1935 non-null   float64
 15  number_pipe__m_dep                     1935 non-null   float64
 16  number_pipe__mobile_wt                 1935 non-null   float64
 17  number_pipe__n_cores                   1935 non-null   float64
 18  number_pipe__pc                        1935 non-null   float64
 19  number_pipe__px_height                 1935 non-null   float64
 20  number_pipe__px_width                  1935 non-null   float64
 21  number_pipe__ram                       1935 non-null   float64
 22  number_pipe__sc_h                      1935 non-null   float64
 23  number_pipe__sc_w                      1935 non-null   float64
 24  number_pipe__talk_time                 1935 non-null   float64
 25  number_pipe__three_g                   1935 non-null   float64
 26  number_pipe__touch_screen              1935 non-null   float64
dtypes: float64(27)
memory usage: 408.3 KB

In [28]:
display(df_analyzed)

,text_pipe__blue_no,text_pipe__blue_yes,text_pipe__four_g_no,text_pipe__four_g_yes,text_pipe__wifi_no_wifi,text_pipe__wifi_wifi,text_pipe__price_range_high cost,text_pipe__price_range_low cost,text_pipe__price_range_medium cost,text_pipe__price_range_very high cost,...,number_pipe__n_cores,number_pipe__pc,number_pipe__px_height,number_pipe__px_width,number_pipe__ram,number_pipe__sc_h,number_pipe__sc_w,number_pipe__talk_time,number_pipe__three_g,number_pipe__touch_screen
0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,-1.107153,-1.309865,-1.408836,-1.150465,0.397885,-0.789575,0.286772,1.490569,-1.790676,-1.003624
1,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,-0.669494,-0.649386,0.580254,1.685934,0.474026,1.111300,-0.636529,-0.744837,0.558448,0.996389
2,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.205824,-0.649386,1.384880,1.059716,0.448027,-0.314357,-0.867355,-0.372269,0.558448,0.996389
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.643483,-0.154026,1.279244,1.220875,0.602167,0.873690,0.517598,0.000298,0.558448,-1.003624
4,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,-1.107153,0.671573,1.261264,-0.100629,-0.658810,-1.027185,-0.867355,0.745434,0.558448,0.996389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1930,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.643483,0.671573,1.292730,1.460311,-1.348726,0.160862,-0.405704,1.490569,0.558448,0.996389
1931,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,-0.231835,-1.144745,0.602729,1.632981,-0.082178,-0.314357,0.979248,0.931718,0.558448,0.996389
1932,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.518801,-1.144745,0.497094,0.866325,0.869591,-0.789575,-1.098180,-1.117405,0.558448,0.996389
1933,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.205824,-0.814506,-0.698608,-1.348460,-1.162087,1.348909,0.979248,1.490569,0.558448,0.996389
1934,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.643483,1.001812,-0.368216,-1.155069,1.670005,1.586519,-0.405704,-1.676256,0.558448,0.996389